repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-encoding-pragma
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
    - id: yapf
      additional_dependencies: [toml]
      args: ['--style=pyproject.toml', '--parallel', '--in-place']
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
